### PR TITLE
Fix pagination LBT01 issue count

### LINKED ISSUE #291: Pagination issue not showing the right numbers when table is paginated with `do_force_pagination`
We need to understand better this mechanism, but the issue comes from LBT01 pagination inside `length(fpags) > 1`

### PR DESCRIPTION
**Pull request by Melkiades**
now the following produces 6 pages with proper counts:
```r
library(chevron)
library(rtables)
res <- run(lbt01, chevron::syn_data)
options(formatter_default_page_number = "{i}/{n}")
cat(export_as_txt(res))
```

Fixes #291

### CODE REVIEW

File: R/pagination.R [hunk 1]
```diff
@@ -1161,16 +1161,21 @@ paginate_to_mpfs <- function(obj,
   ## but we will if we ever allow force_paginate to do horiz
   ## pagination.
   if (length(fpags) > 1) {
-    deep_pag <- lapply(
-      fpags, paginate_to_mpfs,
+    # Correction for case we are entering here (page_by?)
+    if (!is.null(page_num)) {
+      prov_footer(obj) <- head(prov_footer(obj), -1)
+      fpags <- do_forced_paginate(obj)
```
Comment (Melkiades) [inline R/pagination.R:1167]: This is the new fix to #288 and #286

File: R/pagination.R [hunk 2]
```diff
@@ -1161,16 +1161,21 @@ paginate_to_mpfs <- function(obj,
   ## but we will if we ever allow force_paginate to do horiz
   ## pagination.
   if (length(fpags) > 1) {
-    deep_pag <- lapply(
-      fpags, paginate_to_mpfs,
```
Comment (Melkiades) [inline R/pagination.R:1165]: this was the old list pagination which does not work here. We use directly `paginate_mpfs`

**Review by edelarua — APPROVED** [review]
Works great!! Thanks Davide :)

File: R/pagination.R (hunk 1 above)
Comment (gmbecker) [reply R/pagination.R:1167]: It doesn't make sense to call do_forced_paginate(obj), just loop through fpags and reset each of their prov headers...

```
fpags <- lapply(fpags, function(x) {
   prov_footer(x) <- head(prov_footer(x), -1)
   x
})
```

File: R/pagination.R [hunk 3]
```diff
@@ -1161,16 +1161,21 @@ paginate_to_mpfs <- function(obj,
...
+    deep_pag <- paginate_to_mpfs( # what about the other parameters?
+      fpags,
       pg_size_spec = pg_size_spec,
       colwidths = colwidths,
       min_siblings = min_siblings,
       nosplitin = nosplitin,
       verbose = verbose,
       page_num = page_num
     )
-    return(unlist(deep_pag, recursive = FALSE))
```
Comment (gmbecker) [inline R/pagination.R:1173]: this is a breaking change, previously `paginate_to_mpfs` was guaranteed to return a shallow list of pages, now it can return a nested list

File: R/pagination.R (hunk 1 above)
Comment (Melkiades) [reply R/pagination.R:1167]: You are right, I just did not know exactly how it was working do_forced_paginate so I went extremely conservative eheh. We will have to change all of this during the refactoring we talked about yesterday
