### PR TITLE
Fix oneliner error and addition of `basic_listing_mf` for testing

### LINKED ISSUE #259: Fix oneliner self extension bug coming from {rlistings}
See https://github.com/insightsengineering/rlistings/issues/195

### PR DESCRIPTION
**Pull request by Melkiades**
Fixes #259 and #248 and https://github.com/insightsengineering/rlistings/issues/195

### CODE REVIEW

**Review by shajoezhu — CHANGES_REQUESTED** [review]
Hi @Melkiades , seems the test is failing, can you update the test please. Thanks!

**Comment by Melkiades** [comment]
> Hi @Melkiades , seems the test is failing, can you update the test please. Thanks!

Now the bug should be fixed. I added tests for #243 after having added a way to get a fake listing here in formatters for tests

File: R/pagination.R [hunk 1]
```diff
@@ -991,7 +991,7 @@ paginate_indices <- function(obj,
   #                 in the above call, so we need to keep this information in mf_rinfo
   #                 and use it here.
   mfri <- mf_rinfo(mpf)
-  if (NROW(mfri) > 0 && .is_listing(mpf)) {
+  if (NROW(mfri) > 1 && .is_listing(mpf) && length(.keycols_from_listing(obj)) > 0) {
```
Comment (Melkiades) [inline R/pagination.R:994]: This is the main fix for #260

File: R/matrix_form.R [hunk 2]
```diff
@@ -905,7 +917,98 @@ basic_matrix_form <- function(df, parent_path = "root") {
...
+#'   When `NULL`, no key columns are used. Defaults to `c("vs", "gear")` for `mtcars` default dataset.
+#' @return A valid `MatrixPrintForm` object representing `df` as a listing,
+#'   ready for ASCII rendering.
+#'
+#' @examples
+#' mform <- basic_listing_mf(mtcars)
+#' cat(toString(mform))
+#'
+#' @export
+basic_listing_mf <- function(df,
```
Comment (shajoezhu) [inline R/matrix_form.R:948]: hey @Melkiades , what do you think if we move this function to rlistings?

Comment (Melkiades) [reply R/matrix_form.R:948]: This function needs to be here because its purpose is avoiding importing {rlistings} to test listings in {formatters} directly
