### PR TITLE
Add Truetype support and fix col_gap bug

### LINKED ISSUE #261: Support TrueType (non-monospace) fonts in pagination calculations
Support calculation of pagination for non-monospaced fonts.  Allow user to specify fonts in all relevant places and pass them around accordingly through the internals.

### PR DESCRIPTION
**Pull request by gmbecker**
Move fork changes to internal branch for truetype PR. closes #261 #249

### CODE REVIEW

File: R/generics.R [hunk 1]
```diff
@@ -159,52 +177,60 @@ setMethod(
...
+#'   Only used by methods which must calculate span widths after wrapping.
 #'
 #' @return The number of lines needed to render the object `x`.
 #'
 #' @export
 setGeneric(
   "nlines",
-  function(x, colwidths = NULL, max_width = NULL) standardGeneric("nlines")
+  ## XXX TODO come back and add fontspec default value once not having
+  ## it has found all the disconnection breakages
```
Comment (Melkiades) [inline R/generics.R:194]: I do not know exactly what you mean here

File: R/generics.R [hunk 2]
```diff
@@ -159,52 +177,60 @@ setMethod(
...
 #' @rdname nlines
-setMethod("nlines", "character", function(x, colwidths, max_width) {
+setMethod("nlines", "character", function(x, colwidths, max_width, fontspec, col_gap = NULL) {
+  splstr <- strsplit(x, "\n", fixed = TRUE)
   if (length(x) == 0) {
     return(0L)
-  }
+  } ## else if(is.null(colwidths) && is.null(max_width)) { ## don't need wrapping
+  ##   return(length(splstr))
+  ## }
```
Comment (Melkiades) [inline R/generics.R:224]: colwidths is not used in this code, hence the absence of this consideration right? I do not remember exactly why though

File: R/generics.R [hunk 3]
```diff
@@ -651,6 +677,26 @@ setMethod("num_rep_cols", "MatrixPrintForm", function(obj) {
   }
 })
 
+#' @export
+#' @rdname num_rep_cols
+setMethod("num_rep_cols", "MatrixPrintForm", function(obj) obj$num_rep_cols)
+
+#' @export
+#' @param value numeric(1). The new number of columns to repeat.
```
Comment (Melkiades) [inline R/generics.R:685]:
```suggestion
#' @param value (`numeric(1)`)\cr the new number of columns to repeat.
```

File: R/matrix_form.R [hunk 4]
```diff
@@ -167,10 +186,21 @@ disp_from_spans <- function(spans) {
...
 
+.fixup_cinfo <- function(col_df) {
+  if (is.null(col_df$par_extent)) {
+    col_df$par_extent <- 0L
+  }
+  if (is.null(col_df$node_class)) {
+    col_df$node_class <- "Column"
+  }
+  col_df
+}
```
Comment (Melkiades) [inline R/matrix_form.R:197]: it seems this function is not used

File: R/matrix_form.R [hunk 5]
```diff
@@ -317,13 +355,44 @@ MatrixPrintForm <- function(strings = NULL,
 
   ##  ret <- shove_refdf_into_rowinfo(ret)
   if (is.null(colwidths)) {
-    colwidths <- propose_column_widths(ret)
+    colwidths <- propose_column_widths(ret, fontspec = fontspec)
   }
   mf_col_widths(ret) <- colwidths
   ret <- mform_build_refdf(ret)
+  ret <- mpf_infer_cinfo(ret, colpaths = colpaths, fontspec = fontspec)
```
Comment (Melkiades) [inline R/matrix_form.R:362]: why mpf instead of mf? (I guess we can change it if it is internal)

File: R/mpf_exporters.R [hunk 6]
```diff
@@ -520,7 +549,16 @@ export_as_pdf <- function(x,
                           rep_cols = NULL,
                           tf_wrap = TRUE,
                           max_width = NULL,
-                          colwidths = NULL) {
+                          colwidths = NULL,
+                          fontspec = font_spec(font_family, font_size, lineheight),
+                          # colwidths = propose_column_widths(x, indent_size = indent_size, fontspec = fontspec),
```
Comment (Melkiades) [inline R/mpf_exporters.R:554]:
```suggestion
```

File: R/pagination.R [hunk 7]
```diff
@@ -256,13 +276,20 @@ valid_pag <- function(pagdf,
...
+  ## self extent does ***not*** currently include col_gap for columns
   ## we don't include the trailing_sep for guess because if we paginate here it won't be printed
-  sectlines <- if (start == guess) 0L else sum(!is.na(pagdf[start:(guess - 1), "trailing_sep"]))
-  lines <- rowlines + sectlines # guess - start + 1 because inclusive of start
+  ncols <- 0L
+  if (row) {
+    sectlines <- if (start == guess) 0L else sum(!is.na(pagdf[start:(guess - 1), "trailing_sep"]))
+  } else { ## columns
+    ncols <- guess - start + 1 + length(pagdf$reprint_inds[[start]]) ## +1 because its incluive, 5-6 is 2 columns
+    sectlines <- col_gap * (ncols - as.integer(!has_rowlabels)) ## -1 if no row labels
```
Comment (Melkiades) [inline R/pagination.R:290]: this is part of the col_gap fix right?

Comment (gmbecker) [reply R/pagination.R:290]: yes, correct. it was doing ncols so getting an extra colgap in the listings case (whcih doesn't have row labels so needs ncols - 1 colgaps for ncols columns. tables have row labels so they need ncols colgaps

File: R/matrix_form.R [hunk 8]
```diff
@@ -40,7 +40,26 @@ mform_handle_newlines <- function(matform) {
...
+  # TODO probably better if we had a nlines_nowrap fun to be more explicit
+
+  row_nlines <- apply(
+    strmat,
+    1,
+    function(x) {
+      max(
+        vapply(x,
+          nlines,
+          colwidths = NULL,
```
[the remark this answers is not in the document]
Comment (gmbecker) [reply R/matrix_form.R:54]: nlines accepts colwidths because the TableRow method  for it (which live in rtables) needs them to do wrapping to determine numbers of lines. I'm saying here explicitly that no colwidths are being used because we're not operating on an entire row

File: R/matrix_form.R (hunk 4 above)
Comment (gmbecker) [reply R/matrix_form.R:197]: Hmm, surprising but appears to be true, I've taken it out of my local copy and will push

File: R/tostring.R [hunk 9]
```diff
@@ -1118,6 +1638,10 @@ spread_integer <- function(x, len) {
   }
 }
 
+spread_width <- function(x, len) {
+  rep(x / len, len)
+}
```
Comment (Melkiades) [inline R/tostring.R:1643]: if not used we can lose this for now

File: tests/testthat/test-exporters.R [hunk 10]
```diff
@@ -151,18 +151,6 @@ test_that("export_as_txt maintains horizontal separator from table", {
...
-  prov_footer(dfmf) <- c("my", "prov", "footer")
-
-  set_default_page_number("page {i} of {n}")
-  expect_silent(res <- export_as_txt(dfmf, paginate = TRUE, cpp = 60))
-  set_default_page_number(NULL)
-
-  expect_true(grepl("page 1 of 2", res))
-  expect_true(grepl("page 2 of 2", res))
-})
-
```
Comment (Melkiades) [inline tests/testthat/test-exporters.R:165]: This needs to be reinstated. We added it for the issue we described yesterday

File: R/generics.R (hunk 2 above)
Comment (gmbecker) [reply R/generics.R:224]: this looks like it was wrong anyway, as length(splstr) would be length(x) because of how strsplit works, should be either `lengths(splstr)` (note the s) or if x is guaranteed length 1, it could be `length(splstr[[1]])`. But its commented out anyway so I'll just remove the comment

File: tests/testthat/test-exporters.R (hunk 10 above)
Comment (gmbecker) [reply tests/testthat/test-exporters.R:165]: I didn't (intentionally) delete this, when was it added?

File: tests/testthat/test-pagination.R [hunk 11]
```diff
@@ -451,9 +471,20 @@ test_that("rep_cols works as intended for listings and tables", {
   expect_true(grepl(out[51], pattern = "vs")) # vs is repeated
   expect_true(grepl(out[51], pattern = "gear")) # gear is repeated
 
+  ## XXX this doesn't make sense, key cols are always repeated columns
+  ## having a listing with specified key columns and then
+  ## saying the number of rep columns is something else is an anti-pattern
+  ## we should not support. I made it work to not remove a test in my PR, but we should remove this test
```
Comment (Melkiades) [inline tests/testthat/test-pagination.R:477]: I understand what you mean, but as far as we do not impose it manually (i.e. we add a stop with error or a warning) I would test it, so if we change something we need to go back and change the test. Is not suggested but until we do not block this behavior we might want to keep the test. I heard of people wanting to change the sorting of keycols so this can come useful at a certain point

Comment (gmbecker) [reply tests/testthat/test-pagination.R:477]: They can change the sorting of key columns by changing the which columns are key columns, or we can allow them to set a sorting order for key columns, but we really don't want to be in the business of having two completely separate partially overlapping concepts of which columns are repeated

File: R/matrix_form.R (hunk 5 above)
Comment (Melkiades) [reply R/matrix_form.R:362]: Ok, I see; maybe we should make this distinction more explicit and add it to the dev guide (in another issue)

File: R/pagination.R (hunk 7 above)
Comment (Melkiades) [reply R/pagination.R:290]: Super! That was the source of the error then. Thanks for the fix ;)

File: tests/testthat/test-exporters.R (hunk 10 above)
Comment (Melkiades) [reply tests/testthat/test-exporters.R:165]: I think yesterday! It was part of a small but very important hot-fix for page numbers. As we said yesterday, we will have to merge the two logics and move the page numbering at a later step.

**Review by Melkiades — COMMENTED** [review]
For me, this is ready to go. I will go ahead and review {rtables}, but I do not think there will be substantial delays there. If you have bandwidth @ayogasekaram @edelarua @shajoezhu, please take another look and test this PR, too ;)

File: tests/testthat/test-pagination.R (hunk 11 above)
Comment (Melkiades) [reply tests/testthat/test-pagination.R:477]: It makes sense! We can remove the test at a certain point. I would also add some checks to disallow it if we do not want to support it

**Comment by Melkiades** [comment]
last commit fixes https://github.com/insightsengineering/formatters/issues/278

File: R/pagination.R [hunk 12]
```diff
@@ -1161,31 +1279,30 @@ paginate_to_mpfs <- function(obj,
...
       colwidths = colwidths,
       min_siblings = min_siblings,
       nosplitin = nosplitin,
+      fontspec = fontspec,
       verbose = verbose,
+      rep_cols = rep_cols,
       page_num = page_num
     )
-    return(deep_pag)
+    return(unlist(deep_pag, recursive = FALSE))
```
Comment (Melkiades) [inline R/pagination.R:1293]: This needs to be reverted. Fix from yesterday, we can change the prov_footer as you suggested in the other PR (so no rerunning of do_forced_pagination

File: tests/testthat/test-exporters.R (hunk 10 above)
Comment (gmbecker) [reply tests/testthat/test-exporters.R]: I have different code that passes all the checksincluding this reinstated test in the branch now

File: R/pagination.R (hunk 12 above)
Comment (gmbecker) [reply R/pagination.R:1293]: please look at what is in the branch now (when you're back at your desk) it passes the reinstated test

File: R/pagination.R [hunk 13]
```diff
@@ -903,49 +1027,30 @@ paginate_indices <- function(obj,
...
-  ##                   tf_wrap = tf_wrap,
-  ##                   max_width = max_width,
-  ##                   colwidths = colwidths,
-  ##                   min_siblings = min_siblings,
-  ##                   nosplitin = nosplitin,
-  ##                   col_gap = col_gap,
-  ##                   ## not setting num_rep_cols here cause it wont' get it right
-  ##                   verbose = verbose)
-  ##     return(splice_idx_lists(res))
-  ## }
```
Comment (Melkiades) [inline R/pagination.R:930]: I think we can remove this commented code here

File: R/generics.R (hunk 2 above)
Comment (Melkiades) [reply R/generics.R:224]: not removed ;)

File: R/matrix_form.R (hunk 8 above)
[the remark this answers is not in the document]
Comment (Melkiades) [reply R/matrix_form.R:54]: understood, added to description

File: R/pagination.R (hunk 12 above)
Comment (Melkiades) [reply R/pagination.R]: Yes but counts were problematic for other cases. I reinstated the current fix. Will merge the behaviors in the future ;)

**Comment by Melkiades** [comment]
@gmbecker could we add more tests? I think toString is principally affected (Total +359     +82  -1.90%)

File: R/pagination.R [hunk 14]
```diff
@@ -1290,7 +1299,7 @@ paginate_to_mpfs <- function(obj,
       rep_cols = rep_cols,
       page_num = page_num
     )
-    return(unlist(deep_pag, recursive = FALSE))
+    return(deep_pag)
```
Comment (gmbecker) [inline R/pagination.R:1302]: @Melkiades did you test this with multiple page_bys? I'm pretty sure this breaks existing behavior

Comment (Melkiades) [reply R/pagination.R:1302]: Yes! it works fine, also with page numbers

Comment (gmbecker) [reply R/pagination.R:1302]: You're right. I had thought that do_forced_pag was acting recursively but its not; one call is expected to do *all* of the forced pagination, e.g.:


```
> formatters:::do_forced_paginate(tbl)
$F.A

SEX: F
STRATA1: A

———————————————————————————————————————————————————————————————————————————————————
                                            A: Drug X   B: Placebo   C: Combination
———————————————————————————————————————————————————————————————————————————————————
ASIAN                                                                              
  Mean                                        29.00       31.07          33.73     
BLACK OR AFRICAN AMERICAN                                                          
  Mean                                        32.60       32.80          39.33     
WHITE                                                                              
  Mean                                        34.40       33.67          29.67     
AMERICAN INDIAN OR ALASKA NATIVE                                                   
  Mean                                         NA         35.00          38.00     
MULTIPLE                                                                           
  Mean                                         NA           NA             NA      
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER                                          
  Mean                                         NA           NA             NA      
OTHER                                                                              
  Mean                                         NA           NA             NA      
UNKNOWN                                                                            
  Mean                                         NA           NA             NA      

$F.B

SEX: F
STRATA1: B

———————————————————————————————————————————————————————————————————————————————————
                                            A: Drug X   B: Placebo   C: Combination
———————————————————————————————————————————————————————————————————————————————————
ASIAN                                                                              
  Mean                                        29.55       38.73          41.45     
BLACK OR AFRICAN AMERICAN                                                          
  Mean                                        34.33       25.67          27.25     
WHITE                                                                              
  Mean                                        35.00       32.25          33.40     
AMERICAN INDIAN OR ALASKA NATIVE                                                   
  Mean                                        38.33       38.00          36.00     
MULTIPLE                                                                           
  Mean                                         NA           NA             NA      
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER                                          
  Mean                                         NA           NA             NA      
OTHER                                                                              
  Mean                                         NA           NA             NA      
UNKNOWN                                                                            
  Mean                                         NA           NA             NA      



```

File: R/pagination.R (hunk 13 above)
Comment (gmbecker) [reply R/pagination.R:930]: yeah that code has been commented out for a year, which is why I removed it while I was in the function anyway...

**Comment by gmbecker** [comment]
> @gmbecker could we add more tests? I think toString is principally affected (Total +359 +82 -1.90%)

I've added tests for the stuff that was my fault, though it looks like the styler is messing stuff up by moving around nocov comments @cicdguy, see e.g., 

https://github.com/insightsengineering/formatters/blob/ed23f8176b82fe4b351965faa7c734332778047d/R/tostring.R#L145-L149

from coverage report:
Screenshot 2024-06-03 at 1 24 49 PM

(obviously its nice that there is coverage there, but it was supposed to be nocov...)

**Comment by gmbecker** [comment]
@cicdguy is the restyler running unconditionally (my code passed the linter), and what is with the above styler error?

**Comment by shajoezhu** [comment]
let's fix the styling issue. but i think everything else I think is good to go @Melkiades fyi

File: R/tostring.R [hunk 15]
```diff
@@ -122,9 +127,26 @@ close_font_dev <- function() {
   invisible(NULL)
 }
 
+#' @rdname open_font_dev
+#' @export
+debug_font_dev <- function() {
+  message("debugging font device swapping. call undebug_font_dev() to turn debugging back off.")
+  font_dev_state$debug_active <- TRUE
```
Comment (Melkiades) [inline R/tostring.R:135]: Nice Gabe!

**Review by Melkiades — APPROVED** [review]
