### PR TITLE
Hot fix for page number bug

### LINKED ISSUE #286: duplicated page number
pages number are duplicated when object takes more than one page.

```
library(chevron)
library(rtables)
res <- run(lbt01, chevron::syn_data)
withr::with_options(
  list(formatter_default_page_number = "{i}/{n}"),
  cat(export_as_txt(res))
)
```
image

In addition, the `page_num` argument duplicates again the page numbers.

```
withr::with_options(
  list(formatter_default_page_number = "{i}/{n}"),
  cat(export_as_txt(res), page_num = "- page {i} of {n} -")
)
```

image

### LINKED ISSUE #288: Bug in table export
Reproducible example:
```
library(rtables)
lyt <- basic_table() %>%
  split_cols_by("Species") %>%
  analyze("Sepal.Length", afun = function(x) {
    list(
      "mean (sd)" = rcell(c(mean(x), sd(x)), format = "xx.xx (xx.xx)"),
      "range" = diff(range(x))
    )
  })
lyt

tbl <- build_table(lyt, iris)
prov_footer(tbl) <- c("Santa", "is", "real", "!")
export_as_txt(tbl)
```
leads to

```
Error in length(prov_footer(obj)) == 0 || !grepl(page_num, prov_footer(obj),  : 
  'length = 4' in coercion to 'logical(1)'
```

I think there is just a `any()` missing to handle the case where the prov footer is a vector of several elements.

### PR DESCRIPTION
**Pull request by edelarua**
Closes #288

### CODE REVIEW

**Review by ayogasekaram — APPROVED** [review]
lgtm @edelarua!

File: tests/testthat/test-exporters.R [hunk 1]
```diff
@@ -151,6 +151,18 @@ test_that("export_as_txt maintains horizontal separator from table", {
   expect_equal(out, paste0(rep("=", nchar(out)), collapse = ""))
 })
 
+test_that("export_as_txt works with prov footer and page numbers", {
+  dfmf <- basic_matrix_form(mtcars)
+  prov_footer(dfmf) <- c("my", "prov", "footer")
+
+  set_default_page_number("page {i} of {n}")
+  expect_silent(res <- export_as_txt(dfmf, paginate = TRUE, cpp = 60))
```
Comment (Melkiades) [inline tests/testthat/test-exporters.R:159]: good test @edelarua!
