### PR TITLE
Fix var labels when named

### LINKED ISSUE #262: `var_label<-`: assign atomic value (with no attributes)
In a simple terms: `var_label(x) <- var_label(x)` should not modify `x` if it has non-empty labels for all cols. That's not true right now:

``` r
library(formatters)
labels <- letters[1:5]
var_labels(iris) <- labels

old_iris <- iris
var_labels(iris) <- var_labels(iris)

identical(old_iris, iris)
#> [1] FALSE
```

<sup>Created on 2024-02-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Let's analyse why:
``` r
library(formatters)

labels <- letters[1:5]
var_labels(iris) <- labels

old_species_label <- attr(iris[["Species"]], "label")

var_labels(iris) <- var_labels(iris)
new_species_label <- attr(iris[["Species"]], "label")

identical(old_species_label, new_species_label)
#> [1] FALSE
old_species_label
#> [1] "e"
new_species_label
#> Species 
#>     "e"
```

<sup>Created on 2024-02-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

It seems to me that in assign we save a named vector instead of atomic value. Luckily the getter functionality (i.e. `var_label`) handling this correctly but there might be other getters not that smart -> https://github.com/insightsengineering/teal.data/pull/301

Please make a good test case against it.

### PR DESCRIPTION
**Pull request by Melkiades**
Fixes #262 

``` r
library(formatters)
    labels <- letters[1:5]
    var_labels(iris) <- labels
    
    old_iris <- iris
    var_labels(iris) <- var_labels(iris)
    testthat::expect_identical(old_iris, iris)
    var_labels(iris)
#> Sepal.Length  Sepal.Width Petal.Length  Petal.Width      Species 
#>          "a"          "b"          "c"          "d"          "e"
    
    # teal.data
    labels <- letters[1:5]
    var_labels(iris) <- labels
    
    old_iris <- iris
    teal.data::col_labels(iris) <- teal.data::col_labels(iris)
    testthat::expect_identical(old_iris, iris)
    teal.data::col_labels(iris)
#> Sepal.Length  Sepal.Width Petal.Length  Petal.Width      Species 
#>          "a"          "b"          "c"          "d"          "e"
```

<sup>Created on 2024-02-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/labels.R [hunk 1]
```diff
@@ -100,7 +100,7 @@ var_labels <- function(x, fill = FALSE) {
   # across columns of x
   for (j in theseq) {
     attr(x[[j]], "label") <- if (!is.na(value[j])) {
-      value[j]
+      unname(value[j])
```
Comment (pawelru) [inline R/labels.R:103]: did you consider `as.vector()` instead? This would strip _all_ the attributes (including names).

Comment (Melkiades) [reply R/labels.R:103]: It is a good suggestion but I think the values when assigned should not have any particular attribute (it was the source of the problem)

**Review by pawelru — APPROVED** [review]

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks
